name: Greeting Workflow  # Name of the workflow

on: [push]  # Runs whenever you push code to the repository

jobs:
  greet:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu OS

    steps:
      - name: Checkout code  # Step 1: Get the latest code
        uses: actions/checkout@v4

      - name: Say hello  # Step 2: Print a greeting
        run: echo "Hello, GitHub Actions!"

